import tkinter as tk
def show_text():
    name = entry.get()
    result_label.config(text="Hello " + name)
root = tk.Tk()
root.title("User Input App")
label = tk.Label(root, text="Enter your name:")
label.pack()
entry = tk.Entry(root)
entry.pack()
button = tk.Button(root, text="Submit", command=show_text)
button.pack()
result_label = tk.Label(root, text="")
result_label.pack()
root.mainloop()
